[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "HazardousWorld"
versionNumber = "1.5.0"
description = "Adds environmental hazards and protective equipment including Hazmat Suit, Radiation Shield, and Antidote."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-HazardousWorld"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"
CertiFried-TechtonicaFramework = "1.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/HazardousWorld.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
